POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMyIsImlkIjoiNjk0MTkxNzJlYjk0MDM3MzhlOWJhYjVkIiwiaWF0IjoxNzY1OTA0NzYzfQ.ryqG8miAlzYkAaU8lkfwhgJ2jel5rQrZNGvZGpXSfgI

{
    "title": "Me3's Blog",
    "author": "Me3",
    "url": "Me3Blog.com",
    "likes": 333
}